### PR TITLE
Added the link to the deployed page in my README.md file

### PR DESCRIPTION
**Pull request by Fadahunsiseyi**
Here is the link to my deployed page.
https://fadahunsiseyi.github.io/Portfolio-setup-and-mobile-version-skeleton/

### CODE REVIEW

**Review by vechicin — CHANGES_REQUESTED** [review]
# Hi @Fadahunsiseyi  ✋, 

Good job so far! 🔥 
There are some issues that you still need to work on to go to the next project but you are almost there! 🚨 
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights ⚡ 

- [x] Good PR title/description
- [x] Correct GitHub Flow
- [x] Correct use of GitHub pages

## Required Changes ♻️

- [ ] Your mobile version has a strange horizontal scrolling behavior. I think it is due to a fixed width in the `Works` section.

Screen Shot 2022-06-06 at 8 10 05

Kindly fix this.

_Check the comments under the review._

## Optional suggestions 📂 
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by vechicin** [comment]
https://github.com/Fadahunsiseyi/Portfolio-setup-and-mobile-version-skeleton/blob/11c6df123c5f10641379eaa86daeef58b1379b47/README.md?plain=1#L5-L7

Please change the README title and provide a brief description of what the project is about. It'll make your documentation more engaging and professional.

**Comment by vechicin** [comment]
https://github.com/Fadahunsiseyi/Portfolio-setup-and-mobile-version-skeleton/blob/11c6df123c5f10641379eaa86daeef58b1379b47/README.md?plain=1#L15-L17

Please remove the `(if available)` text since there is now a Live Demo available.

**Comment by vechicin** [comment]
https://github.com/Fadahunsiseyi/Portfolio-setup-and-mobile-version-skeleton/blob/11c6df123c5f10641379eaa86daeef58b1379b47/README.md?plain=1#L20-L38

Please provide a detailed set of instructions on how to get a local copy of this project and how to install the unnecessary dependencies for it to run properly. It might seem insignificant now, but it'll be a requirement later on for more complex projects, so it is better to get in the habit of doing so from early on.

**Comment by vechicin** [comment]
https://github.com/Fadahunsiseyi/Portfolio-setup-and-mobile-version-skeleton/blob/11c6df123c5f10641379eaa86daeef58b1379b47/README.md?plain=1#L42-L48

Please change the `Author1` header to your full name. It'll give you more visibility and it'll make your documentation look more professional as well.

**Comment by vechicin** [comment]
https://github.com/Fadahunsiseyi/Portfolio-setup-and-mobile-version-skeleton/blob/11c6df123c5f10641379eaa86daeef58b1379b47/README.md?plain=1#L60-L64

Please provide some actual acknowledgments here. You can mention Microverse and/or the Figma template.

**Review by elyor-doniyorov — APPROVED** [review]
Hi @Fadahunsiseyi, 

In my opinion, your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Pull request merged**
